### ISSUE TITLE
Graphical User Interface?

### ISSUE THREAD

**Issue by trparky** [tylerszabo/RGB-Fusion-Tool#23]
Are there any plans for a graphical user interface and not just a command line tool?

**Comment by tylerszabo** [comment]
No, a GUI is out of scope. This is strictly a command line tool. However a GUI could be written using the .NET wrapper. Since Gigabyte's tool is a GUI tool I'd feel a little redundant writing one unless there's a particular UI to add functionality to.

**Comment by trparky** [comment]
Well I was thinking it would be nice since the Gigabyte GUI is about as buggy as a roach motel.

**Comment by tylerszabo** [comment]
If possible try pinging Gigabyte and ask them to Open Source their GUI. That way we could fork it and contribute patches back.

There's also a fair bit to doing what they're doing: their tool isn't just a GUI it's also a daemon. There is some functionality which requires constantly updating the configuration (like the music mode).

With this particular tool I want to make it do one thing and do it well. I wouldn't rule out one day writing a GUI but if I were to do so I'd write it as a separate project (which is why it's out-of-scope for this repo). ;)

**Comment by trparky** [comment]
OK. Now I need to find out why something else is broken but that's for another issue.

**Comment by tylerszabo** [comment]
:) thanks for giving it a spin, keep the bug reports / feature requests coming. Even for stuff that might seem out of scope it might inspire another tool!
