### ISSUE TITLE
Changing colors depending of GPU/CPU temperature

### ISSUE THREAD

**Issue by lapd1979** [tylerszabo/RGB-Fusion-Tool#57]
I would like to request a color change function depending on the temperature of the processor or video card. Gigabyte motherboard, RGB Fusion 2.0 compatible

**Comment by tylerszabo** [comment]
To do that you'd need to have some other system monitor the CPU temperature and then call into this tool. Because of the startup lag I really need to get around to building the daemonized version; Gigabyte's lack of support of this feature has been demotivating but I'll see if I can find some renewed passion since there are clearly people that want to still use this.

**Comment by tylerszabo** [comment]
I'm going to close this issue as out of scope (monitoring the CPU will not be something handled by this tool); however I do see the need to make improvements to support this behavior.
